### PR TITLE
Update tvm_useBbregister.m to accept more bbregister flags

### PR DESCRIPTION
**Pull request by TommyClausner**
Made a another option that accepts other bbregister flags in order to have more freedom to customize the functionality

### CODE REVIEW

**Comment by TommyClausner** [comment]
hm weird don't know why this was there

**Comment by TommyClausner** [comment]
:D sorry for the requested review - just wondered what the button was doing and so I clicked it :D

**Comment by TimVanMourik** [comment]
Hmm, this is odd, now it gives a diff of the complete file. Maybe it's to do with line endings (CRLF vs. LF). Could you quickly check out if that's causing the difference? If not (or if it takes more than 10 minutes), I'll merge it as the code looks good. 

No worries about the review request, I appreciate it. It's especially useful if you make a WIP (work-in-progress) PR and the status is changed to 'request review'. It's redundant in this case, but on bother.

**Comment by TommyClausner** [comment]
That's indeed strange ... I only have phone atm so I can't check before tomorrow, but I think it could be eol because in `tvm_matrixFromRegisterDatFile.m` the last line has a change because of that as well (tried to fix the not merged commit today but I only copied from linux text editor, so this one line still shows a diff even if there is "none" - maybe it's the same for the usebbregister function)

**Comment by TommyClausner** [comment]
Best would be I properly save the changes from inside matlab tomorrow (just to make sure)

**Comment by TommyClausner** [comment]
All right seems it was indeed the eol characters - should be fixed now (diff looks normal)

**Comment by TimVanMourik** [comment]
Awesome, thanks!

**Pull request merged**
